general:
    data_type: raw
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Volumes/LACIE_SHARE/Percival/Data_lab_october18
raw:
    input: /Volumes/LACIE_SHARE/Percival/2018.12.08_3G/DLSraw/gathered/2018.10.17h1527_seqMode_10hrs_dscrmbld_DLSraw.h5
    metadata_fname: null

    output: *output

    measurement: adccal

    adc: null
    frame: 8
    col: 500
    row: 100

    interactive: True
    method: [viewer]

    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image, viewer]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 60
    row: 10
    interactive: False

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: 2
    frame: null
    col: 100
    row: 100

    interactive: false
    method: [viewer]

    viewer:
        all_cols: True

corrected:
    input: *output
    output: *output

    measurement: adccal

    adc: 2
    frame: 4
    col: 61
    row: 10

    interactive: True

    method: [viewer]

    plot:
        all_cols: False
    viewer:
        all_cols: True
