general:
    data_type: gathered
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Volumes/LACIE_SHARE/Percival/2018.12.08_3G/DLSraw/gathered

raw:
    input: /Volumes/LACIE_SHARE/Percival/2018.12.08_3G/DLSraw/gathered/2018.10.17h1527_seqMode_10hrs_dscrmbld_DLSraw.h5
    metadata_fname: null

    output: *output

    measurement: adccal

    adc: null
    frame: 3
    col: 500
    row: 100
    adc_part: fine

    interactive: False
    method: [viewer]

    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 60
    row: 10
    adc_part: fine
    interactive: False

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: [0]
    frame: null
    col: 40
    row: 100

    adc_part: fine

    method: [plot]

correction:
    input: *output
    output: *output

    measurement: adccal

    adc: [2]
    frame: null
    col: 400
    row: 400

    interactive: False

    method: [plot]
