general:

    data_type: correction

    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:

#    output: &output /Volumes/LACIE_SHARE/Beamtime_17122018/DLSraw/gathered/DLSraw
#    output: &output /Volumes/LACIE_SHARE/Beamtime_17122018/pinhole3
#    input: &input /Volumes/LACIE_SHARE/Beamtime_17122018/ek26
    output: &output /Volumes/LACIE_SHARE/Percival/Data_lab_october18/Fine_scan

raw:
    input: /Volumes/LACIE_SHARE/Percival/2018.12.08_3G/DLSraw/gathered/2018.10.17h1527_seqMode_10hrs_dscrmbld_DLSraw.h5

    metadata_fname: null

    output: *output

    measurement: adccal

    interactive: True
    
    viewer:
        err_below: -0.1

    adc: null

    frame: 2
    col: 500
    row: 100
    adc_part: fine


    interactive: False
    method: [viewer]


    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 60
    row: 10
    adc_part: fine
    interactive: False

    interactive: True
    
    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: [0]
    frame: null
    col: 100
    row: 100

    adc_part: fine
    interactive: false
    method: [viewer]
    viewer:
        all_cols: True


correction:
    input: *output
#    input_dark: *input
    output: *output

    measurement: adccal

    adc: 2
    frame: 3
    col: 530
    row: 10

    adc_part: None

    interactive: True

    method: [plot]

    plot:
        all_cols: True
