hasgeneral:
    data_type: corrected
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Volumes/LACIE_SHARE/Percival/Data_lab_october18/

raw:
    input: /Users/ben/PostDoc/P2M_HDF5/Data_0918/DLSraw/correction/col0-1439_correction.h5
    metadata_fname: null

    output: *output

    measurement: adccal

    adc: null
    frame: 2
    col: 500
    row: 100
    adc_part: fine

    method: [viewer]

    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 60
    row: 10
    adc_part: fine

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: [0]
    frame: null
    col: 40
    row: 100

    adc_part: fine

    method: [plot]

corrected:
    input: *output
    output: *output

    measurement: adccal

    adc: [0]
    frame: null
    col: 40
    row: 100

    method: [plot]
