general:
    data_type: processed
    run: DLSraw

    plot_sample: False
    plot_reset: False
    plot_combined: False

all:
    output: &output /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan

raw:
    input: /Users/ben/PostDoc/P2M_HDF5/Data_lab/VRST/VRST8kto32k_80p_AV_MultiFile060_DLSraw.h5
    metadata_file:  /Users/ben/PostDoc/P2M_HDF5/Data_lab/VRST/file.dat

    output: *output

    measurement: adccal

    adc: null
    frame: 2
    col: 100
    row: 100

    #method: [viewer]
    method: [image, plot_coarse-fine_vs_image]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 100
    row: null

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 10
    row: null

    method: [plot]
