general:
    run_type: gather

    ncols: 1408
    nrows: 1484

    partition: all

gather:
    n_jobs: 2
    n_processes: 1

    time_limit: 00:30:00

process:
    n_jobs: 16
    n_processes: 10

    time_limit: 00:45:00
    test_dict: {"a": 2, "b": 5}
    test_list: ["mystr", 4]

    test_none:
        a_test: None
        b_test: 5
        c_test:
            cc_test: None
            cc_test2: 2
